import requests as rq
from bs4 import BeautifulSoup
url = 'https://myanimelist.net/anime/seasons'
html = requests.get(url)
soup = BeautifulSoup(html.content, 'html.parser')
results=soup.find(id='myanimelist')
shows=results.find_all('div',class_= 'wrapper stacks-challenge-2023-july js-color-pc-constant')
for shows in results
  print(results, end='\n'*2)
  
  title_element = results.find("h3", class_="h3_anime_title")
print(title_element)

results=soup.find(id='myanimelist')
shows=results.find_all('div',class_= 'info')
for results in shows:
  print(results, end='\n'*2)

info_element = results.find("div", class_="info")
print(info_element)

  
import os

def draw_chart(title, date, stream_service, output_path):

    chart_path = os.path.join(output_path, "{}_{}_courses_collisions.tex"
                                            .format(title, date))
                                            
    width = 277/(len(courses)+1)
    height = 180/(len(courses)+1)
