import requests
from bs4 import BeautifulSoup
url ='https://myanimelist.net/anime/season'
html = requests.get(url)

soup = BeautifulSoup(html.content, 'html.parser')

results=soup.find(id='myanimelist')
shows=results.find_all("div",class_= "title-text")
for results in shows:
  print(results, end='\n'*2)
  
results=soup.find(id='myanimelist')
shows=results.find_all('div',class_= 'info')
for results in shows:
  print(results, end='\n'*2)

results=soup.find(id='myanimelist')
shows=results.find_all('h2',class_= 'h2_anime_title')
for results in shows:
  print(results, end='\n'*2)

  
import os

def draw_chart(title, date, stream_service, output_path):

    chart_path = os.path.join(output_path, "{}_{}_courses_collisions.tex"
                                            .format(title, date))
                                            
    width = 277/(len(courses)+1)
    height = 180/(len(courses)+1)
